global_vars:
  - name: gb_date_short
    type: date
    params:
      # e.g. "30/06/2023"
      format: "%d/%m/%Y"
matches:
  - trigger: ";shortdate"
    replace: "{{gb_date_short}}"
  - trigger: ";longdate"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/date.py"
  - trigger: ";now"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "## %H:%M:%S\n"
