matches:
  - trigger: ";resume"
    replace: "résumé"
    word: true
    propagate_case: true
  - trigger: ";resumes"
    replace: "résumés"
    word: true
    propagate_case: true
  - trigger: "pokemon"
    replace: "pokémon"
    word: true
    propagate_case: true
  - trigger: "naive"
    replace: "naïve"
    word: true
    propagate_case: true
  - trigger: "cafe"
    replace: "café"
    word: true
    propagate_case: true
  - triggers: [";e/", ";/e"]
    replace: "é"
    word: true
    propagate_case: true
  - triggers: [";l/", ";/l"]
    replace: "ł"
    word: true
    propagate_case: true
  - trigger: "deja vu"
    replace: "déjà vu"
    word: true
    propagate_case: true
  - triggers: [";u:", ";:u"]
    replace: "ü"
    word: true
    propagate_case: true
  - trigger: ";uber"
    replace: "über"
    word: true
    propagate_case: true
  - trigger: ";turkey"
    replace: "Türkiye"
    word: true
    propagate_case: true
# Swedish character shortcuts
  - trigger: ";ae"
    replace: "ä"
    propagate_case: true
  - trigger: ";oe"
    replace: "ö"
    propagate_case: true
  - trigger: ";aa"
    replace: "å"
    propagate_case: true
  - trigger: ";`e"
    replace: "é"
    propagate_case: true
